open System.IO

let sample = """............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"""

assert (Day08.Part1.run sample = 14)
assert (Day08.Part2.run sample = 34)

let input = File.ReadAllText "input.txt"

printfn $"Part1: %i{Day08.Part1.run input}"
printfn $"Part2: %i{Day08.Part2.run input}"
